---
log_level: debug-color
introspection_addr: ""
http_listen_addr: ":6000"
updaters: {}
indexer:
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  max_conn_pool: 100
  migrations: true
notifier:
  connstring: host=clair-db port=5432 user=clair dbname=clair sslmode=disable
  migrations: true
  delivery_interval: 5s
  poll_interval: 15s
  # webhook:
  #   target: "http://webhook/"
  #   callback: "http://clair-notifier/notifier/api/v1/notifications"
  amqp:
    direct: true
    exchange:
      name: ""
      type: "direct"
      durable: true
      auto_delete: false
    uris: ["amqp://guest:guest@clair-rabbitmq:5672/"]
    routing_key: "notifications"
    callback: "http://clair-notifier/notifier/api/v1/notifications"
metrics:
  name: "prometheus"
